apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: jixifood
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 4100
    targetPort: 4100
  type: LoadBalancer