apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: jixifood  # Add the namespace
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer