apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: jixifood
  labels:
    app: postgres
    tier: database
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        tier: database
        environment: development
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d/ 
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data 
        readinessProbe:
          exec:
            command:
            - pg_isready
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: init-sql
        configMap:
          name: postgres-init-sql
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: jixifood-pvc