apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jixifood-pvc
  namespace: jixifood 
  labels:
    app: jixifood
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi