apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service
  namespace: jixifood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      containers:
      - name: menu-service
        image: thewhiterabbit94/jf_ms:latest
        ports:
        - containerPort: 4200