apiVersion: v1
kind: Service
metadata:
  name: menu-service
  namespace: jixifood
spec:
  selector:
    app: menu-service
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200
  type: LoadBalancer